Repository BroadleafCommerce/BootStarter, pull requests merged in 2023-02, with the labels that each got.

#29 Update springboot and spring
  pom.xml
Labels: type-enhancement

#30 Change version of thymeleaf-layout-dialect dependency
  pom.xml
Labels: severity-major, type-security

#31 Upgrade jackson with updated property
  pom.xml
Labels: type-security
